version: "3.8"
services:
  node:
    image: node:21-alpine3.18
    container_name: node
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
